### Jhon Doe - Tenant 1
POST http://localhost:8080/auth/realms/codeblue/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest&client_secret=c74a6357-d5a4-451d-ae30-47a09db7a53c&grant_type=password&username=jhon@codeblue.com&password=123456

### Jane Doe - Tenant 2
POST http://localhost:8080/auth/realms/codeblue/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest&client_secret=c74a6357-d5a4-451d-ae30-47a09db7a53c&grant_type=password&username=jane@codeblue.com&password=123456

###

POST http://localhost:3333/accounts
Content-Type: application/json

{
  "name": "Account 1",
  "subdomain": "tenant1"
}

###
POST http://localhost:3333/accounts
Content-Type: application/json

{
  "name": "Account 2",
  "subdomain": "tenant2"
}

###
GET http://localhost:3333/accounts
Accept: application/json

###
POST http://localhost:3333/transactions
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "payment_date": "2021-01-01",
  "name": "New ticket",
  "description": "Description",
  "category": "category1",
  "amount": 30,
  "type": "debit"
}

###
GET http://localhost:3333/transactions
Authorization: Bearer {{access_token}}
Accept: application/json

###
